### ISSUE TITLE
Something is not right with the types

### ISSUE THREAD

**Issue by standup75** [jshemas/openGraphScraper#171] opened 2023-03-08 01:50 UTC
Here is my code:
```
async function openGraphScrapper(url: string) {
  const { result: data } = await ogs({ url })
  console.log(data)
  return {
    imageUrl: data.ogImageURL,
    title: data.ogTitle,
    url: data.ogUrl,
  }
}
```

When I try with `https://seth.blog` the console.log returns this

```
{
  ogType: 'website',
  ogTitle: "Seth's Blog",
  ogDescription: "Seth Godin's Blog on marketing, tribes and respect",
  ogUrl: 'https://seths.blog/',
  ogSiteName: "Seth's Blog",
  ogLocale: 'en_US',
  twitterCard: 'summary_large_image',
  twitterSite: '@ThisIsSethsBlog',
  twitterCreator: '@ThisIsSethsBlog',
  ogImage: {
    height: '628px',
    type: 'jpg',
    url: 'https://149521506.v2.pressablecdn.com/wp-content/themes/godin/img/og-images/seth.jpg',
    width: '1200px'
  },
  favicon: 'https://149521506.v2.pressablecdn.com/wp-content/themes/godin/img/favicons/favicon.ico',
  charset: 'utf8',
  requestUrl: 'https://seth.blog',
  success: true
}
```

So it seems to me that if I want the image, I need to get it from `data.ogImage.url`, but that is not part of the return type. Is it missing?

**Comment by jshemas** [comment] 2023-03-13 03:38
Hello, I can look into it.

**Comment by jshemas** [comment] 2023-03-15 00:42
So I think the issue is because `ogImage` can be a `string`, `object` and `array`. I'm not sure how to support all three of these datatypes. In the next version of `openGraphScraper` I'm planning on update all properties to just be one datatype so we don't have issues like this in the future.

**Comment by jshemas** [comment] 2023-05-07 00:19
Hello. `open-graph-scraper@6.0.0` is now live and now `ogImage` will always be the `ImageObject[]` type which will have a `url` property. Let me know if this fixes your problem.

**Comment by jshemas** [comment] 2023-05-16 01:34
Closing this for now. Please reopen the issue if needed.

**Closed by jshemas** 2023-05-16 01:34 UTC
